name: Daily 20 Commits

on:
  schedule:
    - cron: "0 0 * * *"  # jalan setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --local user.email "joshua.plk08@gmail.com"
          git config --local user.name "JoshNells13"

      - name: Make 20 commits
        run: |
          for i in {1..20}
          do
            echo "Update ke-$i at $(date)" >> update.txt
            git add update.txt
            git commit -m "Auto commit ke-$i"
            echo "Commit ke-$i done!"
          done

      - name: Push changes
        run: git push
